# action.yml
name: 'Dpl (dee-pee-ell)'
description: 'Deploy using Dpl (dee-pee-ell) with GitHub Actions'
branding:
  icon: "upload-cloud"
  color: "green"
inputs:
  provider:
    description: 'Sets the provider you want to deploy to'
    required: true

  base-dir:
    description: 'The path to start by'
    required: false

  app:
    description: 'Heroku app name'
    required: false

  api-key:
    description: 'Heroku API Key'
    required: false

outputs:
  result: # id of output
    description: 'The dpl result'
runs:
  using: "node12"
  main: "dist/index.js"